# If you put one webhook URL here, all data will be sent to the same webhook. 
# If you put the same amount as tokens, the data from each token will be sent to the corresponding webhook. 
# If you put multiple but not the same amount as there are tokens, the same data will be sent to all webhooks.
# For example, if you want to put 3 webhooks, you can put the following:
# webhookURLs: ["webhookURL1", "webhookURL2", "webhookURL3"]
webhookURLs: []
webhookName: "EarnApp Earnings Watcher"
webhookImage: "https://s3-eu-west-1.amazonaws.com/tpd/logos/6135e9dd9f3c85001f1088e8/0x0.png"
# If you want to put 3 tokens, you can put the following:
# tokens: ["token1", "token2", "token3"]
tokens: [] # the oauth-refresh-token of the EarnApp account(s)
delay: 600 # delay in seconds after the hour that it should update. The EarnApp dashboard doesn't update bang on the hour, so don't set this too low or you'll miss the data. I've noticed it update at 8/9 mins past.
ratelimitWait: 60 # if the API ratelimit is hit, how long should we wait before trying again?
perDevice: false # if you want to send data per device, set this to true. NOT IMPLEMENTED YET

appUpdateSettings:
  enabled: true # if you want to send messages when there is a new EarnApp version, set this to true.
  embedSettings:
    embed: true # if you want embeds to be sent, set this to true. If false, the program will send the update data as normal text
    inline: true # if you want the embeds to be inline, set this to true. If false, the program will send the embed's fields in a line instead of next to each other.
    colour: "77ac97" # the colour of the line at the side of the embed. You can find a list of colours here: https://www.w3schools.com/colors/colors_picker.asp
    title: "EarnApp Earnings Watcher" # the title of the embed
    titleURL: "https://github.com/Woodie-07/EarnApp-Earnings-Watcher" # the url that the title will link to
    description: "App update" # the description of the embed
    authorName: "Woodie" # the name of the author of the embed
    authorURL: "https://woodie.cf" # the url that the author's name will link to
    authorIcon: "https://cdn.discordapp.com/avatars/851073836152651777/eed752ca4ba02d9d97e87fda6752faab.png?size=1024" # the url of the author's icon
    image: "" # the url of the image that will be displayed in the embed
    thumbnail: "https://s3-eu-west-1.amazonaws.com/tpd/logos/6135e9dd9f3c85001f1088e8/0x0.png" # the url of the thumbnail that will be displayed in the embed
    footer: "EarnApp Earnings Watcher {{version}} {{state}} by Woodie" # the footer of the embed
    footerIcon: "https://pngimg.com/uploads/github/github_PNG40.png"
  shownInfo:
    windows:
      enabled: true # if you want to show windows updates, set this to true.
      title: "Windows Update" # the title of the embed
      text: "Version changed from {{win_old_version}} to {{win_new_version}}" # the value of the field
    mac:
      enabled: true # if you want to show mac updates, set this to true.
      title: "Mac Update" # the title of the embed
      text: "Version changed from {{mac_old_version}} to {{mac_new_version}}" # the value of the field

redeemRequestSettings:
  enabled: true # if you want to send messages when there is a new redeem request, set this to true.
  embedSettings:
    embed: true # if you want embeds to be sent, set this to true. If false, the program will send the redeem request data as normal text
    inline: true # if you want the embeds to be inline, set this to true. If false, the program will send the embed's fields in a line instead of next to each other.
    colour: "77ac97" # the colour of the line at the side of the embed. You can find a list of colours here: https://www.w3schools.com/colors/colors_picker.asp
    title: "EarnApp Earnings Watcher" # the title of the embed
    titleURL: "https://github.com/Woodie-07/EarnApp-Earnings-Watcher" # the url that the title will link to
    description: "Redeem request" # the description of the embed
    authorName: "Woodie" # the name of the author of the embed
    authorURL: "https://woodie.cf" # the url that the author's name will link to
    authorIcon: "https://cdn.discordapp.com/avatars/851073836152651777/eed752ca4ba02d9d97e87fda6752faab.png?size=1024" # the url of the author's icon
    image: "" # the url of the image that will be displayed in the embed
    thumbnail: "https://s3-eu-west-1.amazonaws.com/tpd/logos/6135e9dd9f3c85001f1088e8/0x0.png" # the url of the thumbnail that will be displayed in the embed
    footer: "EarnApp Earnings Watcher {{version}} {{state}} by Woodie" # the footer of the embed
    footerIcon: "https://pngimg.com/uploads/github/github_PNG40.png"
  shownInfo:
    amount:
      enabled: true # if you want to show the amount of the redeem request, set this to true.
      title: "Amount" # the title of the embed
      text: "${{amount}}" # the value of the field
    referralsBonus:
      enabled: true # if you want to show the referrals bonus of the redeem request, set this to true.
      title: "Referrals Bonus" # the title of the embed
      text: "${{referrals_bonus}}" # the value of the field
    promotionsBonus:
      enabled: true # if you want to show the promotions bonus of the redeem request, set this to true.
      title: "Promotions Bonus" # the title of the embed
      text: "${{promotions_bonus}}" # the value of the field
    status:
      enabled: true # if you want to show the status of the redeem request, set this to true.
      title: "Status" # the title of the embed
      text: "{{status}}" # the value of the field
    id:
      enabled: true # if you want to show the id of the redeem request, set this to true.
      title: "ID" # the title of the embed
      text: "{{id}}" # the value of the field
    createdAt:
      enabled: true # if you want to show the created at of the redeem request, set this to true.
      title: "Created At" # the title of the embed
      text: "{{created_at}}" # the value of the field
    email:
      enabled: true # if you want to show the email of the redeem request, set this to true.
      title: "Email" # the title of the embed
      text: "{{email}}" # the value of the field
    paymentMethod:
      enabled: true # if you want to show the payment method of the redeem request, set this to true.
      title: "Payment Method" # the title of the embed
      text: "{{payment_method}}" # the value of the field

newDeviceSettings:
  enabled: true # if you want to send messages when there is a new device, set this to true.
  embedSettings:
    embed: true # if you want embeds to be sent, set this to true. If false, the program will send the new device data as normal text
    inline: true # if you want the embeds to be inline, set this to true. If false, the program will send the embed's fields in a line instead of next to each other.
    colour: "77ac97" # the colour of the line at the side of the embed. You can find a list of colours here: https://www.w3schools.com/colors/colors_picker.asp
    title: "EarnApp Earnings Watcher" # the title of the embed
    titleURL: "https://github.com/Woodie-07/EarnApp-Earnings-Watcher" # the url that the title will link to
    description: "New device" # the description of the embed
    authorName: "Woodie" # the name of the author of the embed
    authorURL: "https://woodie.cf" # the url that the author's name will link to
    authorIcon: "https://cdn.discordapp.com/avatars/851073836152651777/eed752ca4ba02d9d97e87fda6752faab.png?size=1024" # the url of the author's icon
    image: "" # the url of the image that will be displayed in the embed
    thumbnail: "https://s3-eu-west-1.amazonaws.com/tpd/logos/6135e9dd9f3c85001f1088e8/0x0.png" # the url of the thumbnail that will be displayed in the embed
    footer: "EarnApp Earnings Watcher {{version}} {{state}} by Woodie" # the footer of the embed
    footerIcon: "https://pngimg.com/uploads/github/github_PNG40.png"
  shownInfo:
    id:
      enabled: true # if you want to show the id of the new device, set this to true.
      title: "ID" # the title of the embed
      text: "{{id}}" # the value of the field
    name:
      enabled: true # if you want to show the name of the new device, set this to true.
      title: "Name" # the title of the embed
      text: "{{name}}" # the value of the field
    bw:
      enabled: true # if you want to show the bandwidth of the new device, set this to true.
      title: "Bandwidth" # the title of the embed
      text: "{{bw_gb}} GB" # the value of the field
    country:
      enabled: true # if you want to show the country of the new device, set this to true.
      title: "Country" # the title of the embed
      text: "{{country}}" # the value of the field
    earned:
      enabled: true # if you want to show the earned amount of the new device, set this to true.
      title: "Earned" # the title of the embed
      text: "${{earned}}" # the value of the field
    totalEarned:
      enabled: true # if you want to show the total earned amount of the new device, set this to true.
      title: "Total Earned" # the title of the embed
      text: "${{total_earned}}" # the value of the field
    ips:
      enabled: true # if you want to show the ips of the new device, set this to true.
      title: "IPs" # the title of the embed
      separator: ", " # the separator of the ips.
      text: "{{ips}}" # the value of the field
    rate:
      enabled: true # if you want to show the rate of the new device, set this to true.
      title: "Rate" # the title of the embed
      text: "${{rate}}/GB" # the value of the field
    totalBw:
      enabled: true # if you want to show the total bandwidth of the new device, set this to true.
      title: "Total Bandwidth" # the title of the embed
      text: "${{total_bw_gb}} GB" # the value of the field

balanceUpdateSettings:
  enabled: true # if you want to send balance updates, set this to true.
  sendIfNotChanged: true # if you want to send balance updates even if the balance hasn't changed, set this to true.
  embedSettings:
    embed: true # if you want embeds to be sent, set this to true. If false, the program will send the earnings data as normal text
    inline: true # if you want the embeds to be inline, set this to true. If false, the program will send the embed's fields in a line instead of next to each other.
    colour: "77ac97" # the decimal colour of the side of the embed
    colourIfNotChanged: "ff0000" # the colour of the line at the side of the embed that will be shown if the balance has not changed. You can find a list of colours here: https://www.w3schools.com/colors/colors_picker.asp
    title: "EarnApp Earnings Watcher" # the title of the embed
    titleURL: "https://github.com/Woodie-07/EarnApp-Earnings-Watcher" # the url that the title will link to
    description: "Balance update" # the description of the embed
    descriptionIfNotChanged: "Balance has not changed" # the description of the embed that will be shown if the balance has not changed
    authorName: "Woodie" # the name of the author of the embed
    authorURL: "https://woodie.cf" # the url that the author's name will link to
    authorIcon: "https://cdn.discordapp.com/avatars/851073836152651777/eed752ca4ba02d9d97e87fda6752faab.png?size=1024" # the url of the author's icon
    image: "" # the url of the image that will be displayed in the embed
    thumbnail: "https://s3-eu-west-1.amazonaws.com/tpd/logos/6135e9dd9f3c85001f1088e8/0x0.png" # the url of the thumbnail that will be displayed in the embed
    footer: "EarnApp Earnings Watcher {{version}} {{state}} by Woodie" # the footer of the embed
    footerIcon: "https://pngimg.com/uploads/github/github_PNG40.png"
  shownInfo:
    accountEmail:
      enabled: true # if you want to show the email of the account, set this to true
      title: "Account Email" # the title of the field
      text: "{{account_email}}" # the value of the field
    accountName:
      enabled: true # if you want to show the name of the account, set this to true
      title: "Account Name" # the title of the info
      text: "{{account_name}}" # the text of the info
    hourEarned: 
      enabled: true # show balance earned in past hour
      title: "Hourly Earnings" # the title of the info
      text: "${{hour_earned}}" # the text of the info
    hourEarnedAverage:
      enabled: true # show average balance earned in past hour
      title: "Hourly Earnings Average" # the title of the info
      text: "${{hour_earned_average}}" # the text of the info
    refEarnings: 
      enabled: true # show amount earned from referrals
      title: "Referrals Earned" # the title of the info
      text: "${{ref_earned}}" # the text of the info
    promotionsEarnings: 
      enabled: true # show amount earned from promotions
      title: "Promotions Earned" # the title of the info
      text: "${{promo_earned}}" # the text of the info
    hourTraffic: 
      enabled: true # show amount of traffic in past hour
      title: "Hourly Traffic" # the title of the info
      text: "{{hour_traffic_gb}} GB" # the text of the info
    balance: 
      enabled: true # show account balance
      title: "Balance" # the title of the info
      text: "${{balance}}" # the text of the info
    lifetimeBalance: 
      enabled: true # show account lifetime balance
      title: "Lifetime Balance" # the title of the info
      text: "${{lifetime_balance}}" # the text of the info
    activeDevices: 
      enabled: true # show amount of active devices
      title: "Active Devices" # the title of the info
      separator: " | " # the separator between the devices
    deviceTypeActive: 
      enabled: true # show the type of active devices, if enabled activeDevices.enabled will be ignored
    inactiveDevices: 
      enabled: true # show amount of inactive devices
      title: "Inactive Devices" # the title of the info
      separator: " | " # the separator between the devices
    deviceTypeInactive: 
      enabled: true # show the type of inactive devices
    totalDevices: 
      enabled: true # show the amount of devices
      title: "Total Devices" # the title of the info
      separator: " | " # the separator between the devices
    deviceTypeTotal: 
      enabled: true # show the type of devices
